Change Bundler update approach for CI
There were errors in Windows:

```
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>call gem install bundler
ERROR:  Error installing bundler:
"bundle" from bundler conflicts with C:/tools/ruby/bin/bundle
```